model = "gpt-5.3-codex"
approval_policy = "on-request"
sandbox_mode = "workspace-write"
model_reasoning_effort = "xhigh"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
env_http_headers = { CONTEXT7_API_KEY = "CONTEXT7_API_KEY" }

[mcp_servers.gh_grep]
url = "https://mcp.grep.app"

[mcp_servers.exa]
url = "https://mcp.exa.ai/mcp"
bearer_token_env_var = "EXA_API_KEY"

[mcp_servers.notion]
url = "https://mcp.notion.com/mcp"

[mcp_servers.figma-desktop]
url = "http://127.0.0.1:3845/mcp"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"

[features]
multi_agent = true
